import {
  YouthDisciplineCategoryInfo,
  YouthDisciplineCriterion,
  YouthDisciplineSettings,
  YouthViolationRecord
} from '../types/youthDiscipline';

export const YOUTH_DISCIPLINE_CATEGORIES: YouthDisciplineCategoryInfo[] = [
  {
    id: 'CHUYEN_CAN',
    code: 'A',
    name: 'A. Chuyên cần',
    order: 1,
    icon: 'Clock',
    color: 'emerald'
  },
  {
    id: 'TRANG_PHUC_TAC_PHONG',
    code: 'B',
    name: 'B. Trang phục – Tác phong',
    order: 2,
    icon: 'Shirt',
    color: 'blue'
  },
  {
    id: 'Y_THUC_KY_LUAT',
    code: 'C',
    name: 'C. Ý thức – Kỷ luật',
    order: 3,
    icon: 'ShieldAlert',
    color: 'rose'
  },
  {
    id: 'VE_SINH_MOI_TRUONG',
    code: 'D',
    name: 'D. Vệ sinh – Môi trường',
    order: 4,
    icon: 'Trash2',
    color: 'amber'
  },
  {
    id: 'HOC_TAP',
    code: 'E',
    name: 'E. Học tập',
    order: 5,
    icon: 'BookOpen',
    color: 'indigo'
  },
  {
    id: 'NEN_NEP_TAP_THE',
    code: 'F',
    name: 'F. Nền nếp tập thể',
    order: 6,
    icon: 'Users',
    color: 'purple'
  }
];

export const DEFAULT_YOUTH_CRITERIA: YouthDisciplineCriterion[] = [
  // A. CHUYÊN CẦN
  {
    id: 'crit_cc_1',
    code: 'CC01',
    name: 'Nghỉ học không phép',
    category: 'CHUYEN_CAN',
    categoryName: 'Chuyên cần',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Nghỉ học không có đơn xin phép hoặc giấy xác nhận hợp lệ của phụ huynh',
    order: 1
  },
  {
    id: 'crit_cc_2',
    code: 'CC02',
    name: 'Đi học muộn',
    category: 'CHUYEN_CAN',
    categoryName: 'Chuyên cần',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Đến trường hoặc vào lớp sau hiệu lệnh trống vào giờ',
    order: 2
  },
  {
    id: 'crit_cc_3',
    code: 'CC03',
    name: 'Bỏ tiết / Trốn tiết',
    category: 'CHUYEN_CAN',
    categoryName: 'Chuyên cần',
    severity: 'Nghiêm trọng',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Tự ý rời khỏi trường hoặc không có mặt trong giờ học',
    order: 3
  },
  {
    id: 'crit_cc_4',
    code: 'CC04',
    name: 'Ra khỏi lớp không lý do',
    category: 'CHUYEN_CAN',
    categoryName: 'Chuyên cần',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Tự ý ra ngoài trong giờ học khi chưa được sự cho phép của giáo viên',
    order: 4
  },

  // B. TRANG PHỤC – TÁC PHONG
  {
    id: 'crit_tp_1',
    code: 'TP01',
    name: 'Không mặc đúng đồng phục',
    category: 'TRANG_PHUC_TAC_PHONG',
    categoryName: 'Trang phục – Tác phong',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Không mặc áo sơ mi đồng phục, áo khoác đồng phục hoặc áo thể dục theo lịch',
    order: 5
  },
  {
    id: 'crit_tp_2',
    code: 'TP02',
    name: 'Không đeo thẻ học sinh',
    category: 'TRANG_PHUC_TAC_PHONG',
    categoryName: 'Trang phục – Tác phong',
    severity: 'Nhẹ',
    minusPoints: 1,
    affectCompetition: true,
    status: 'active',
    description: 'Không đeo thẻ học sinh trong suốt thời gian có mặt tại trường',
    order: 6
  },
  {
    id: 'crit_tp_3',
    code: 'TP03',
    name: 'Trang phục không đúng quy định',
    category: 'TRANG_PHUC_TAC_PHONG',
    categoryName: 'Trang phục – Tác phong',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Mặc quần rách, quần bó sát, áo ngắn, không sơ vin khi có quy định',
    order: 7
  },
  {
    id: 'crit_tp_4',
    code: 'TP04',
    name: 'Đầu tóc / tác phong không phù hợp nội quy',
    category: 'TRANG_PHUC_TAC_PHONG',
    categoryName: 'Trang phục – Tác phong',
    severity: 'Vừa',
    minusPoints: 3,
    affectCompetition: true,
    status: 'active',
    description: 'Nhuộm tóc màu nổi bật, cắt tóc kiểu dị biệt, trang điểm đậm, sơn móng tay/chân',
    order: 8
  },

  // C. Ý THỨC – KỶ LUẬT
  {
    id: 'crit_kl_1',
    code: 'KL01',
    name: 'Không thực hiện nội quy trường',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Cố ý không chấp hành quy định chung của nhà trường',
    order: 9
  },
  {
    id: 'crit_kl_2',
    code: 'KL02',
    name: 'Gây mất trật tự',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Nói chuyện to, làm việc riêng, gây ồn ào ảnh hưởng tiết học và giờ tự quản',
    order: 10
  },
  {
    id: 'crit_kl_3',
    code: 'KL03',
    name: 'Không chấp hành yêu cầu của giáo viên',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Nghiêm trọng',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Thái độ vô lễ, cãi lại hoặc chống đối hiệu lệnh của thầy cô giáo',
    order: 11
  },
  {
    id: 'crit_kl_4',
    code: 'KL04',
    name: 'Có hành vi thiếu văn hóa, nói tục chửi thề',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Phát ngôn thiếu chuẩn mực, văng tục hoặc xúc phạm bạn bè',
    order: 12
  },
  {
    id: 'crit_kl_5',
    code: 'KL05',
    name: 'Vi phạm an toàn giao thông (không đội MBH / đi xe phân khối lớn)',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Rất nghiêm trọng',
    minusPoints: 10,
    affectCompetition: true,
    status: 'active',
    description: 'Không đội mũ bảo hiểm khi đi xe đạp điện/xe máy, đi xe phân khối lớn không đúng độ tuổi',
    order: 13
  },
  {
    id: 'crit_kl_6',
    code: 'KL06',
    name: 'Hút thuốc lá / thuốc lá điện tử trong hoặc gần trường',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Rất nghiêm trọng',
    minusPoints: 10,
    affectCompetition: true,
    status: 'active',
    description: 'Tàng trữ, sử dụng hoặc lôi kéo người khác hút thuốc lá, thuốc lá điện tử',
    order: 14
  },
  {
    id: 'crit_kl_7',
    code: 'KL07',
    name: 'Gây gổ, xích mích, bạo lực học đường',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Rất nghiêm trọng',
    minusPoints: 15,
    affectCompetition: true,
    status: 'active',
    description: 'Đánh nhau, xúi giục, quay clip bạo lực học đường',
    order: 15
  },

  // D. VỆ SINH – MÔI TRƯỜNG
  {
    id: 'crit_vs_1',
    code: 'VS01',
    name: 'Không trực nhật lớp học',
    category: 'VE_SINH_MOI_TRUONG',
    categoryName: 'Vệ sinh – Môi trường',
    severity: 'Nhẹ',
    minusPoints: 3,
    affectCompetition: true,
    status: 'active',
    description: 'Không quét lớp, không lau bảng, không đổ rác trước giờ học',
    order: 16
  },
  {
    id: 'crit_vs_2',
    code: 'VS02',
    name: 'Xả rác bừa bãi',
    category: 'VE_SINH_MOI_TRUONG',
    categoryName: 'Vệ sinh – Môi trường',
    severity: 'Nhẹ',
    minusPoints: 3,
    affectCompetition: true,
    status: 'active',
    description: 'Vứt rác không đúng nơi quy định trong lớp, hành lang, sân trường',
    order: 17
  },
  {
    id: 'crit_vs_3',
    code: 'VS03',
    name: 'Không giữ gìn vệ sinh lớp học',
    category: 'VE_SINH_MOI_TRUONG',
    categoryName: 'Vệ sinh – Môi trường',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Lớp học bừa bộn, rác trong ngăn bàn, bục giảng bẩn',
    order: 18
  },
  {
    id: 'crit_vs_4',
    code: 'VS04',
    name: 'Vi phạm vệ sinh khu vực được phân công',
    category: 'VE_SINH_MOI_TRUONG',
    categoryName: 'Vệ sinh – Môi trường',
    severity: 'Nhẹ',
    minusPoints: 3,
    affectCompetition: true,
    status: 'active',
    description: 'Không dọn vệ sinh khu vực sân trường, cầu thang được phân công trực nhật',
    order: 19
  },

  // E. HỌC TẬP
  {
    id: 'crit_ht_1',
    code: 'HT01',
    name: 'Không chuẩn bị bài / không làm bài tập',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Không học bài cũ, không hoàn thành bài tập về nhà',
    order: 20
  },
  {
    id: 'crit_ht_2',
    code: 'HT02',
    name: 'Không mang đủ sách vở, đồ dùng học tập',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Nhẹ',
    minusPoints: 1,
    affectCompetition: true,
    status: 'active',
    description: 'Thiếu sách giáo khoa, vở ghi hoặc đồ dùng học tập theo yêu cầu bộ môn',
    order: 21
  },
  {
    id: 'crit_ht_3',
    code: 'HT03',
    name: 'Không thực hiện nhiệm vụ học tập',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Không tham gia hoạt động nhóm, lười phát biểu xây dựng bài',
    order: 22
  },
  {
    id: 'crit_ht_4',
    code: 'HT04',
    name: 'Sử dụng điện thoại trong giờ học khi chưa được phép',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Lướt mạng xã hội, chơi game, xem video trong tiết học khi giáo viên không cho phép',
    order: 23
  },
  {
    id: 'crit_ht_5',
    code: 'HT05',
    name: 'Gian lận trong kiểm tra, thi cử',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Nghiêm trọng',
    minusPoints: 10,
    affectCompetition: true,
    status: 'active',
    description: 'Mang tài liệu, xem bài bạn, sử dụng thiết bị tra cứu trái phép trong giờ thi',
    order: 24
  },

  // F. NỀN NẾP TẬP THỂ
  {
    id: 'crit_tt_1',
    code: 'TT01',
    name: 'Không tham gia chào cờ đầu tuần',
    category: 'NEN_NEP_TAP_THE',
    categoryName: 'Nền nếp tập thể',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Vắng mặt trong lễ chào cờ đầu tuần không có lý do chính đáng',
    order: 25
  },
  {
    id: 'crit_tt_2',
    code: 'TT02',
    name: 'Không thực hiện nghiêm túc sinh hoạt tập thể',
    category: 'NEN_NEP_TAP_THE',
    categoryName: 'Nền nếp tập thể',
    severity: 'Nhẹ',
    minusPoints: 2,
    affectCompetition: true,
    status: 'active',
    description: 'Mất trật tự trong giờ chào cờ, sinh hoạt dưới cờ, hoạt động trải nghiệm',
    order: 26
  },
  {
    id: 'crit_tt_3',
    code: 'TT03',
    name: 'Không thực hiện nhiệm vụ trực tuần',
    category: 'NEN_NEP_TAP_THE',
    categoryName: 'Nền nếp tập thể',
    severity: 'Vừa',
    minusPoints: 5,
    affectCompetition: true,
    status: 'active',
    description: 'Lớp trực tuần không đánh trống, không chuẩn bị âm thanh, không dọn nhà vòm',
    order: 27
  },
  {
    id: 'crit_tt_4',
    code: 'TT04',
    name: 'Vi phạm quy định khi tham gia hoạt động Đoàn',
    category: 'NEN_NEP_TAP_THE',
    categoryName: 'Nền nếp tập thể',
    severity: 'Nhẹ',
    minusPoints: 3,
    affectCompetition: true,
    status: 'active',
    description: 'Đến muộn, bỏ về sớm hoặc không hoàn thành phân công hoạt động phong trào Đoàn',
    order: 28
  }
];

export const DEFAULT_YOUTH_SETTINGS: YouthDisciplineSettings = {
  id: 'youth_discipline_config_default',
  schoolYear: '2026–2027',
  baseScore: 100,
  allowRanking: true,
  allowPublicResults: true,
  thresholdGood: 90,
  thresholdFair: 75,
  thresholdPass: 55,
  autoLockDayOfWeek: 6, // Thứ 7
  defaultEvaluatorRole: 'BI_THU_DOAN'
};

export const SAMPLE_YOUTH_VIOLATIONS: YouthViolationRecord[] = [
  {
    id: 'yv_sample_1',
    schoolYear: '2026–2027',
    weekNumber: 3,
    monthNumber: 9,
    violationDate: '2026-09-21',
    violationTime: '07:15',
    periodSlot: 'Sáng (Đầu giờ)',
    classId: 'c_10a1',
    className: '10A1',
    studentId: 'st_10a1_01',
    studentName: 'Nguyễn Văn An',
    studentCode: 'HS10A101',
    criterionId: 'crit_cc_2',
    criterionCode: 'CC02',
    criterionName: 'Đi học muộn',
    category: 'CHUYEN_CAN',
    categoryName: 'Chuyên cần',
    severity: 'Nhẹ',
    minusPoints: 2,
    location: 'Cổng trường',
    content: 'Đến trường lúc 07h15, muộn 15 phút so với giờ tập trung',
    recordedBy: 'can_bo_doan_1',
    recordedByName: 'Đội Cờ đỏ Khối 12',
    recordedByRole: 'CÁN BỘ ĐOÀN',
    confirmedBy: 'bi_thu_doan',
    confirmedByName: 'Bí thư Đoàn trường',
    confirmedAt: '2026-09-21T08:00:00Z',
    status: 'DA_XAC_NHAN',
    notes: 'Học sinh hứa sẽ đi sớm hơn',
    createdAt: '2026-09-21T07:20:00Z'
  },
  {
    id: 'yv_sample_2',
    schoolYear: '2026–2027',
    weekNumber: 3,
    monthNumber: 9,
    violationDate: '2026-09-21',
    violationTime: 'Tiết 1',
    periodSlot: 'Sáng',
    classId: 'c_11a2',
    className: '11A2',
    studentId: 'st_11a2_05',
    studentName: 'Trần Thị Mai',
    studentCode: 'HS11A205',
    criterionId: 'crit_tp_2',
    criterionCode: 'TP02',
    criterionName: 'Không đeo thẻ học sinh',
    category: 'TRANG_PHUC_TAC_PHONG',
    categoryName: 'Trang phục – Tác phong',
    severity: 'Nhẹ',
    minusPoints: 1,
    location: 'Lớp học 11A2',
    content: 'Quên mang thẻ học sinh khi vào lớp',
    recordedBy: 'can_bo_doan_2',
    recordedByName: 'Ủy viên BCH Đoàn',
    recordedByRole: 'CÁN BỘ ĐOÀN',
    confirmedBy: 'bi_thu_doan',
    confirmedByName: 'Bí thư Đoàn trường',
    confirmedAt: '2026-09-21T11:30:00Z',
    status: 'DA_XAC_NHAN',
    createdAt: '2026-09-21T07:45:00Z'
  },
  {
    id: 'yv_sample_3',
    schoolYear: '2026–2027',
    weekNumber: 3,
    monthNumber: 9,
    violationDate: '2026-09-22',
    violationTime: '14:30',
    periodSlot: 'Chiều (Tiết 2)',
    classId: 'c_12a3',
    className: '12A3',
    studentId: 'st_12a3_12',
    studentName: 'Lê Hoàng Nam',
    studentCode: 'HS12A312',
    criterionId: 'crit_ht_4',
    criterionCode: 'HT04',
    criterionName: 'Sử dụng điện thoại trong giờ học khi chưa được phép',
    category: 'HOC_TAP',
    categoryName: 'Học tập',
    severity: 'Vừa',
    minusPoints: 5,
    location: 'Phòng học 12A3',
    content: 'Lướt mạng xã hội trong tiết học Vật lý',
    recordedBy: 'gv_bo_mon',
    recordedByName: 'GV Giảng dạy & Đoàn TN',
    recordedByRole: 'GIÁO VIÊN',
    confirmedBy: 'bi_thu_doan',
    confirmedByName: 'Bí thư Đoàn trường',
    confirmedAt: '2026-09-22T17:00:00Z',
    status: 'DA_XAC_NHAN',
    notes: 'Đã tạm giữ điện thoại và bàn giao GVCN',
    createdAt: '2026-09-22T14:40:00Z'
  },
  {
    id: 'yv_sample_4',
    schoolYear: '2026–2027',
    weekNumber: 3,
    monthNumber: 9,
    violationDate: '2026-09-23',
    violationTime: '06:55',
    periodSlot: 'Sáng',
    classId: 'c_10a2',
    className: '10A2',
    studentId: 'st_10a2_08',
    studentName: 'Hoàng Quốc Bảo',
    studentCode: 'HS10A208',
    criterionId: 'crit_kl_5',
    criterionCode: 'KL05',
    criterionName: 'Vi phạm an toàn giao thông (không đội MBH / đi xe phân khối lớn)',
    category: 'Y_THUC_KY_LUAT',
    categoryName: 'Ý thức – Kỷ luật',
    severity: 'Rất nghiêm trọng',
    minusPoints: 10,
    location: 'Cổng trường',
    content: 'Đi xe máy điện không đội mũ bảo hiểm',
    recordedBy: 'co_do_1',
    recordedByName: 'Đội Thanh niên Tình nguyện ATGT',
    recordedByRole: 'CÁN BỘ ĐOÀN',
    confirmedBy: 'bi_thu_doan',
    confirmedByName: 'Bí thư Đoàn trường',
    confirmedAt: '2026-09-23T08:00:00Z',
    status: 'DA_XAC_NHAN',
    notes: 'Đã lập biên bản ATGT tại cổng trường',
    createdAt: '2026-09-23T07:05:00Z'
  }
];
